{
	"schema_version": "1.6.0",
	"id": "RHSA-2024:5530",
	"modified": "2024-11-25T23:44:21Z",
	"published": "2024-09-30T20:25:31Z",
	"related": [
		"CVE-2024-6345"
	],
	"summary": "Red Hat Security Advisory: python-setuptools security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::baseos",
				"name": "platform-python-setuptools",
				"purl": "pkg:rpm/redhat/platform-python-setuptools"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:39.2.0-8.el8_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:5530.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::baseos",
				"name": "python-setuptools",
				"purl": "pkg:rpm/redhat/python-setuptools"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:39.2.0-8.el8_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:5530.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::baseos",
				"name": "python3-setuptools",
				"purl": "pkg:rpm/redhat/python3-setuptools"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:39.2.0-8.el8_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:5530.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::baseos",
				"name": "python3-setuptools-wheel",
				"purl": "pkg:rpm/redhat/python3-setuptools-wheel"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:39.2.0-8.el8_10"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:5530.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:5530"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#important"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2297771"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_5530.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-6345"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2024-6345"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-6345"
		},
		{
			"type": "ARTICLE",
			"url": "https://github.com/pypa/setuptools/commit/88807c7062788254f654ea8c03427adc859321f0"
		},
		{
			"type": "ARTICLE",
			"url": "https://huntr.com/bounties/d6362117-ad57-4e83-951f-b8141c6e7ca5"
		}
	]
}
