{
	"schema_version": "1.6.0",
	"id": "RHSA-2024:9985",
	"modified": "2024-11-26T03:52:03Z",
	"published": "2024-11-25T09:53:21Z",
	"related": [
		"CVE-2024-37891"
	],
	"summary": "Red Hat Security Advisory: RHOSP 17.1.4 (python-urllib3) security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:openstack:17.1::el8",
				"name": "python-urllib3",
				"purl": "pkg:rpm/redhat/python-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.25.10-7.el8ost"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:9985.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:openstack:17.1::el8",
				"name": "python3-urllib3",
				"purl": "pkg:rpm/redhat/python3-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.25.10-7.el8ost"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:9985.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:9985"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2292788"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_9985.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-37891"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2024-37891"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
		}
	]
}
