{
	"schema_version": "1.6.0",
	"id": "RHSA-2024:9922",
	"modified": "2024-12-18T10:10:47Z",
	"published": "2024-11-25T09:53:17Z",
	"related": [
		"CVE-2024-37891"
	],
	"summary": "Red Hat Security Advisory: python3.11-urllib3 security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:H/PR:H/UI:N/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:rhel_eus:9.4::appstream",
				"name": "python3.11-urllib3",
				"purl": "pkg:rpm/redhat/python3.11-urllib3"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:1.26.12-2.el9_4.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:9922.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:9922"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2292788"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_9922.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-37891"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2024-37891"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-37891"
		}
	]
}
