{
	"schema_version": "1.6.0",
	"id": "RHSA-2024:3552",
	"modified": "2024-11-24T15:52:37Z",
	"published": "2024-09-14T03:14:36Z",
	"related": [
		"CVE-2024-3651"
	],
	"summary": "Red Hat Security Advisory: python-idna security and bug fix update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:rhel_aus:8.6::baseos",
				"name": "python-idna",
				"purl": "pkg:rpm/redhat/python-idna"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.5-5.el8_6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:3552.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_aus:8.6::baseos",
				"name": "python3-idna",
				"purl": "pkg:rpm/redhat/python3-idna"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.5-5.el8_6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:3552.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_e4s:8.6::baseos",
				"name": "python-idna",
				"purl": "pkg:rpm/redhat/python-idna"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.5-5.el8_6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:3552.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_e4s:8.6::baseos",
				"name": "python3-idna",
				"purl": "pkg:rpm/redhat/python3-idna"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.5-5.el8_6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:3552.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_tus:8.6::baseos",
				"name": "python-idna",
				"purl": "pkg:rpm/redhat/python-idna"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.5-5.el8_6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:3552.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:rhel_tus:8.6::baseos",
				"name": "python3-idna",
				"purl": "pkg:rpm/redhat/python3-idna"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.5-5.el8_6.1"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2024:3552.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:3552"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2274779"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2024/rhsa-2024_3552.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2024-3651"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2024-3651"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2024-3651"
		}
	]
}
