{
	"schema_version": "1.6.0",
	"id": "RHSA-2021:4161",
	"modified": "2024-09-13T15:44:55Z",
	"published": "2024-09-13T15:44:55Z",
	"related": [
		"CVE-2020-28493"
	],
	"summary": "Red Hat Security Advisory: python-jinja2 security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "python-jinja2",
				"purl": "pkg:rpm/redhat/python-jinja2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.10.1-3.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2021:4161.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:8::appstream",
				"name": "python3-jinja2",
				"purl": "pkg:rpm/redhat/python3-jinja2"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.10.1-3.el8"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2021:4161.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2021:4161"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/8.5_release_notes/"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1928707"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2021/rhsa-2021_4161.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2020-28493"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2020-28493"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-28493"
		}
	]
}
