{
	"schema_version": "1.6.0",
	"id": "RHBA-2020:4195",
	"modified": "2024-10-27T18:22:01Z",
	"published": "2024-09-13T18:09:34Z",
	"related": [
		"CVE-2020-1753"
	],
	"summary": "Red Hat Bug Fix Advisory: Ansible 2.8.16 release for Ansible Engine 2.8",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:R/S:U/C:H/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:ansible_engine:2.8::el7",
				"name": "ansible",
				"purl": "pkg:rpm/redhat/ansible"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.8.16-1.el7ae"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHBA-2020:4195.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:ansible_engine:2.8::el8",
				"name": "ansible",
				"purl": "pkg:rpm/redhat/ansible"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:2.8.16-1.el8ae"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHBA-2020:4195.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHBA-2020:4195"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2020/rhba-2020_4195.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2020-1753"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1811008"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2020-1753"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2020-1753"
		}
	]
}
