{
	"schema_version": "1.6.0",
	"id": "RHSA-2012:0369",
	"modified": "2024-09-15T19:41:00Z",
	"published": "2024-09-15T19:41:00Z",
	"related": [
		"CVE-2012-0805"
	],
	"summary": "Red Hat Security Advisory: python-sqlalchemy security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:6::server",
				"name": "python-sqlalchemy",
				"purl": "pkg:rpm/redhat/python-sqlalchemy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:0.5.5-3.el6_2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2012:0369.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:6::workstation",
				"name": "python-sqlalchemy",
				"purl": "pkg:rpm/redhat/python-sqlalchemy"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:0.5.5-3.el6_2"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2012:0369.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2012:0369"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=783305"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/security/data/csaf/v2/advisories/2012/rhsa-2012_0369.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2012-0805"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2012-0805"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2012-0805"
		}
	]
}
