{
	"schema_version": "1.6.0",
	"id": "RHSA-2020:0851",
	"modified": "2024-11-22T12:52:04Z",
	"published": "2024-09-18T04:12:07Z",
	"related": [
		"CVE-2018-18074",
		"CVE-2018-20060",
		"CVE-2019-11236"
	],
	"summary": "Red Hat Security Advisory: python-virtualenv security update",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:7::client",
				"name": "python-virtualenv",
				"purl": "pkg:rpm/redhat/python-virtualenv"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:15.1.0-4.el7_7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2020:0851.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:7::computenode",
				"name": "python-virtualenv",
				"purl": "pkg:rpm/redhat/python-virtualenv"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:15.1.0-4.el7_7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2020:0851.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:7::server",
				"name": "python-virtualenv",
				"purl": "pkg:rpm/redhat/python-virtualenv"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:15.1.0-4.el7_7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2020:0851.json"
			}
		},
		{
			"package": {
				"ecosystem": "Red Hat:enterprise_linux:7::workstation",
				"name": "python-virtualenv",
				"purl": "pkg:rpm/redhat/python-virtualenv"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0:15.1.0-4.el7_7"
						}
					]
				}
			],
			"database_specific": {
				"source": "https://security.access.redhat.com/data/osv/RHSA-2020:0851.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2020:0851"
		},
		{
			"type": "ARTICLE",
			"url": "https://access.redhat.com/security/updates/classification/#moderate"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1643829"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1649153"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1700824"
		},
		{
			"type": "ADVISORY",
			"url": "https://security.access.redhat.com/data/csaf/v2/advisories/2020/rhsa-2020_0851.json"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2018-18074"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2018-18074"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2018-18074"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2018-20060"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2018-20060"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2018-20060"
		},
		{
			"type": "REPORT",
			"url": "https://access.redhat.com/security/cve/CVE-2019-11236"
		},
		{
			"type": "ADVISORY",
			"url": "https://www.cve.org/CVERecord?id=CVE-2019-11236"
		},
		{
			"type": "ADVISORY",
			"url": "https://nvd.nist.gov/vuln/detail/CVE-2019-11236"
		}
	]
}
